name: Build

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: build dist
        run: |
          npm install -g yarn
          yarn install
          yarn build
      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: experiment-helper-mobile
          endpoint: https://oss-cn-hangzhou.aliyuncs.com
          folder: ./dist/build/h5
